// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docSidebar: [
	'index',
	{
      type: 'category',
      label: '基础理论',
      items: [{type: 'autogenerated', dirName: 'theory'},],
	},
	{
      type: 'category',
      label: '设备指南',
      items: [{type: 'autogenerated', dirName: 'equipment'},],
	},
    {
      type: 'category',
      label: 'NINA',
      items: [
        {
          type: 'category',
          label: 'Documentation',
          items: [
            { type: 'doc', id: 'NINA/index', label: 'Introduction' },
            { type: 'doc', id: 'NINA/requirements', label: 'Requirements' },
            {
              type: 'category',
              label: 'Tabs',
              items: [
                { type: 'doc', id: 'NINA/tabs/equipment/equipment', label: 'Overview' },
                {
                  type: 'category',
                  label: 'Equipment',
                  items: [
                    { type: 'doc', id: 'NINA/tabs/equipment/camera', label: 'Camera' },
                    { type: 'doc', id: 'NINA/tabs/equipment/filterwheel', label: 'Filter Wheel' },
                    { type: 'doc', id: 'NINA/tabs/equipment/focuser', label: 'Focuser' },
                    { type: 'doc', id: 'NINA/tabs/equipment/rotator', label: 'Rotator' },
                    { type: 'doc', id: 'NINA/tabs/equipment/telescope', label: 'Telescope' },
                    { type: 'doc', id: 'NINA/tabs/equipment/guider', label: 'Guider' },
                    { type: 'doc', id: 'NINA/tabs/equipment/switch', label: 'Switch' },
                    { type: 'doc', id: 'NINA/tabs/equipment/flatpanel', label: 'Flat Panel' },
                    { type: 'doc', id: 'NINA/tabs/equipment/weather', label: 'Weather' },
                    { type: 'doc', id: 'NINA/tabs/equipment/dome', label: 'Dome' },
                    { type: 'doc', id: 'NINA/tabs/equipment/safetymonitor', label: 'Safety Monitor' },
                  ],
                },
                { type: 'doc', id: 'NINA/tabs/skyatlas', label: 'Sky Atlas' },
                { type: 'doc', id: 'NINA/tabs/framing', label: 'Framing Assistant' },
                { type: 'doc', id: 'NINA/tabs/flatwizard', label: 'Flat Wizard' },
                { type: 'doc', id: 'NINA/tabs/sequencer', label: 'Sequencer' },
                { type: 'doc', id: 'NINA/tabs/imaging', label: 'Imaging' },
                {
                  type: 'category',
                  label: 'Options',
                  items: [
                    { type: 'doc', id: 'NINA/tabs/options/general', label: 'General' },
                    { type: 'doc', id: 'NINA/tabs/options/equipment', label: 'Equipment' },
                    { type: 'doc', id: 'NINA/tabs/options/autofocus', label: 'Autofocus' },
                    { type: 'doc', id: 'NINA/tabs/options/dome', label: 'Dome' },
                    { type: 'doc', id: 'NINA/tabs/options/imaging', label: 'Imaging' },
                    { type: 'doc', id: 'NINA/tabs/options/platesolving', label: 'Plate Solving' },
                  ],
                },
                {
                  type: 'category',
                  label: 'Plugins',
                  items: [
                    { type: 'doc', id: 'NINA/tabs/plugins/installed', label: 'Installed' },
                    { type: 'doc', id: 'NINA/tabs/plugins/available', label: 'Available' },
                  ],
                },
              ],
            },
			        {
              type: 'category',
              label: 'Sequencer',
              items: [
                { type: 'doc', id: 'NINA/sequencer/overview', label: 'Overview' },
                {
                  type: 'category',
                  label: 'Legacy Sequencer',
                  items: [
                    { type: 'doc', id: 'NINA/sequencer/simple/simple', label: 'Overview' },
                    { type: 'doc', id: 'NINA/sequencer/simple/sequencing', label: 'Sequencing' },
                  ],
                },
                {
                  type: 'category',
                  label: 'Advanced Sequencer',
                  items: [
                    { type: 'doc', id: 'NINA/sequencer/advanced/advanced', label: 'Overview' },
                    { type: 'doc', id: 'NINA/sequencer/advanced/instructions', label: 'Instructions' },
                    { type: 'doc', id: 'NINA/sequencer/advanced/conditions', label: 'Loop Conditions' },
                    { type: 'doc', id: 'NINA/sequencer/advanced/triggers', label: 'Triggers' },
                    { type: 'doc', id: 'NINA/sequencer/advanced/expressions', label: 'Expressions (NINA 3.3)' },
                    { type: 'doc', id: 'NINA/sequencer/advanced/simpletoadvanced', label: 'From Legacy To Advanced' },
                  ],
                },
              ],
            },
            {
              type: 'category',
              label: 'Advanced Topics',
              items: [
                { type: 'doc', id: 'NINA/advanced/autofocus', label: 'Auto-Focus' },
                { type: 'doc', id: 'NINA/advanced/meridianflip', label: 'Automated Meridian Flip' },
                { type: 'doc', id: 'NINA/advanced/camerasimulator', label: 'Camera Simulator' },
                { type: 'doc', id: 'NINA/advanced/bulbshutter', label: 'Bulb Shutter Control' },
                { type: 'doc', id: 'NINA/advanced/dithering', label: 'Dithering' },
                { type: 'doc', id: 'NINA/advanced/backlashmeasurement', label: 'Focuser Backlash Measurement' },
                { type: 'doc', id: 'NINA/advanced/framingassistant', label: 'Framing Assistant' },
                {
                  type: 'category',
                  label: 'File Formats',
                  items: [
                    { type: 'doc', id: 'NINA/advanced/file_formats/tiff', label: 'TIFF' },
                    { type: 'doc', id: 'NINA/advanced/file_formats/fits', label: 'FITS' },
                    { type: 'doc', id: 'NINA/advanced/file_formats/xisf', label: 'XISF' },
                  ],
                },
                { type: 'doc', id: 'NINA/advanced/guiding', label: 'Guiding' },
                { type: 'doc', id: 'NINA/advanced/platesolving', label: 'Plate Solving' },
              ],
            },
            {
              type: 'category',
              label: 'Troubleshooting',
              items: [
                { type: 'doc', id: 'NINA/troubleshooting/general', label: 'General' },
                { type: 'doc', id: 'NINA/troubleshooting/ascom_connection_issues', label: 'ASCOM Connection Issues' },
                { type: 'doc', id: 'NINA/troubleshooting/ioptron', label: 'iOptron Mount Setup' },
                { type: 'doc', id: 'NINA/troubleshooting/eqmod', label: 'EQMOD Setup' },
                { type: 'doc', id: 'NINA/troubleshooting/altair_dualgain', label: 'Altair Dual Gain' },
                { type: 'doc', id: 'NINA/troubleshooting/planetarium', label: 'Planetarium Setup' },
                { type: 'doc', id: 'NINA/troubleshooting/qhy_driver_update', label: 'QHY Driver' },
                { type: 'doc', id: 'NINA/troubleshooting/render_issues', label: 'Display Issues' },
                { type: 'doc', id: 'NINA/troubleshooting/folder_browser_only_desktop', label: 'Folder browser only showing desktop' },
              ],
            },
            { type: 'doc', id: 'NINA/glossary', label: 'Glossary' },
            { type: 'doc', id: 'NINA/license', label: 'License' },
            { type: 'doc', id: 'NINA/3rd-party-license', label: '3rd-Party-Licenses' },
          ],
        },
        {
          type: 'category',
          label: 'Quick Start',
          items: [
            { type: 'doc', id: 'NINA/quickstart/uioverview', label: 'UI Overview' },
            { type: 'doc', id: 'NINA/quickstart/equipment', label: 'Connecting Your Equipment' },
            { type: 'doc', id: 'NINA/quickstart/settings', label: 'Finalizing Settings' },
            { type: 'doc', id: 'NINA/quickstart/focusing', label: 'Focusing' },
            { type: 'doc', id: 'NINA/quickstart/sequence', label: 'Starting a Sequence' },
          ],
        },
        {
          type: 'category',
          label: 'Contributing',
          items: [
            // { type: 'doc', id: 'NINA/contributing/contributing', label: 'Enhance documentation' },
            { type: 'doc', id: 'NINA/contributing/howtosetupdev', label: 'How to setup the development environment' },
            { type: 'doc', id: 'NINA/contributing/localization', label: 'Localization' },
            { type: 'doc', id: 'NINA/contributing/plugins', label: 'Plugins' },
            { type: 'doc', id: 'NINA/contributing/ecosystem', label: 'Ecosystem' },
          ],
        },
      ],
    },
  ],
  
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
